- cloudevents-binding.md
- primer.md
Add a CloudEvents binding document.
The CloudEvents Binding for CDEvents defines how
CDEvents are mapped to CloudEvents headers and body.
Add a primer document.
The primer document gives an overview of the CDEvents
spec, it's architecture, goals and design decisions.
Both documents are only stubs for now.
> Placeholder for binding and primer docs

- .gitignore
- README.md
- continuous-deployment-pipeline-events.md
- continuous-integration-pipeline-events.md
- core.md
- source-code-version-control.md
- spec.md
Import the draft spec as-is from github.com/cdfoundation/sig-events,
except for minor lint and spelling fixes.
> Import draft spec

- .github/workflows/main.yml
- tools/.notableofcontents
- tools/update-toc.sh
Add a tool to generate and manage the TOC of various docs.
We might want to add a CI job that checks that the TOC is
up to date once we start adding specs.
> Add a tool to manage the TOC of various docs

- governance.md
Add an initial governance.md to define the bootstrap governance
committee
> Add initial bootstrap governance

- primer.md
This amendment to the primer aims to explain the relations between CDEvents and CloudEvents. Reworded version of  [SIG Events meeting note from 19th of October 2021](https://hackmd.io/2FRGlw9fTMmKN1OQUVvguA#Meeting-19th-October).
Signed-off-by: Mattias Linnér <mattias.linner@ericsson.com>
> Explain relations to CloudEvents

- _index.md
- cloudevents-binding.md
- continuous-deployment-pipeline-events.md
- continuous-integration-pipeline-events.md
- core.md
- primer.md
- source-code-version-control.md
- spec.md
> Add front matter for website

- primer.md
- roadmap.md
Add a roadmap doc for cdevents that include the mission and vision
for the project too.
> Add a roadmap and vision doc for cdevents

- continuous-deployment-pipeline-events.md
- continuous-integration-pipeline-events.md
- core.md
- source-code-version-control.md
- spec.md
According to the CloudEvents spec, https://github.com/cloudevents/spec/blob/v1.0.1/spec.md
the event type SHOULD be prefixed with a reverse-DNS name.
The prefix domain dictates the organisation which defines
the semantics of the event type.
Since CDEvents owns the `cdevents.dev` domain, and has a website
hosted on that domain, we should use that domain in the event
types as well.
Related to #21 
> Use dev.cdevents as root for event types

- spec.md
Restructure a the spec root page, add more sections and introduce
the initial terminology, including subjects and actions.
This provides the basis for restructuring the vocabulary and
defining the schemas that will be used to build the SDKs.
Partially addresses: #12
Related to: #11
> Reformat the spec root page, add subjects and actions

- spec.md
Expand the definition of mandatory attributes by adding syntax
details and examples.
Introduce the "version" as a mandatory attribute.
Add the subject as an optional attribute as discussed in the WG.
> Add syntax details for attributes in CDEvents

- core.md
- source-code-version-control.md
Reformat the source code version control stage page to match what
done for the core stage. No spec changes.
Part of #13
> Format source code events same as core

- cloudevents-binding.md
As discussed in the WG, we're not going to have a CDEvents binary
mode, so remove it from the specification.
Organise links in the cloudevents binding doc.
> Remove binary mode from CDEvents

- continuous-integration-pipeline-events.md
- primer.md
- schemas/artifactpackaged.json
- source-code-version-control.md
The artifact packaged event is typically produced by the build process, and should provide details about the source the artifact was built from.
While working on the artifact change field, I realised that for the change and branch events the id + source combination should also contain the repository details, otherwise it wouldn't uniquely identify a change.
I added a note in the change/branch event section and updated the examples accordingly. I think there is still value in have a repository field in those events, but I marked it as optional (it was mandatory before).
> Add change to the artifact packaged event

- continuous-deployment-pipeline-events.md
- schemas/pipelinerunqueued.json
- schemas/servicedeployed.json
- schemas/servicerolledback.json
- schemas/serviceupgraded.json
Add the artifactId to some of the service events:
- deployed
- upgraded
- rolledback
The model is that one service is associated to one artifact. As already documented in the primer.md, this is a simplified model and it may change in future versions.
The format of the artifactId in the examples is consistent with the rest of the spec for now. All artifactIds will align to the purl format in an upcoming pull request.
Fixes: #58
> Add artifactId to service events

- continuous-deployment-pipeline-events.md
- continuous-integration-pipeline-events.md
- primer.md
- spec.md
Specify that artifact IDs are in the package-url format: https://github.com/package-url/purl-spec
Fixes: #38
> Add package-url format for artifact IDs

- continuous-deployment-pipeline-events.md
- source-code-version-control.md
The service environment is a ref to an environment in the schemas and it should be a ref, i.e. a combination of id and source because the id is only unique when combined to the source.
As in other cases, if the source of the environment is the same as the source of the main subject (the service), it may be omitted.
The spec only includes today the environmentId as string - update it to be an object (reference to environment).
> Update service environment to be a ref

- primer.md
> Add reference to DORA metrics in the primer.md

- _index.md
- cloudevents-binding.md
- continuous-deployment-pipeline-events.md
- continuous-integration-pipeline-events.md
- core.md
- primer.md
- source-code-version-control.md
- spec.md
- wpaper.md
Signed-off-by: Terry Cox <terry@bootstrap.je>
- Implemented a descriptive landing page for the documentation, with context and description
- Added icons to docs
- Disabled auto-generated page list
PR is 'look and feel' only and does not impact specification content.
> Refresh Documentation Main Page

- spec.md
Fixes the primer links in spec after the content migration to cdevents.dev
> Fix primer links

- continuous-integration.md
The field is already documented for the subject and included in the jsonschema, but when I added it a missed to update the artifact packaged field table in the markdown spec.
Fixes: #115
> Add the change field to the artifact packaged

- continuous-integration.md
- examples/artifact_signed.json
- schemas/artifactsigned.json
Add a new predicate for artifacts, the reflect the signature of the artifact being generated. Different artifacts have different strategies for storing signatures, so the signature is a very generic string attribute which is only available in the artifact.signed event.
> Add the artifact signed event

- examples/change_created.json
- schemas/changecreated.json
- source-code-version-control.md
This commit adds a new optional field to the dev.cdevents.change.created
event.  This field, description, should be used to describe the change,
e.g. a GitHub PR.
An example of the description field could be something like
"This PR addresses a new bug that was introduced in some PR"
resolves #151
Signed-off-by: benjamin-j-powell <benjamin_j_powell@apple.com>
> Add change.created description field

- .github/pull_request_template.md
A couple links seems to be outdated which results in 404s. This commit addresses that by pointing to the CDEvents primer website with the appropriate sub-links.
> Update pull request template with working links

- CODEOWNERS
Add maintainers file with the existing members of the [spec-maintainers](https://github.com/orgs/cdevents/teams/spec-maintainers) team
> Add maintainers file

- continuous-integration.md
- examples/artifact_packaged.json
- examples/artifact_published.json
- schemas/artifactpackaged.json
- schemas/artifactpublished.json
- tools/verify-examples.sh
Artifact packaged and/or published events may include a link to a published SBOM. Since there is no default storage location for such SBOM documents, CDEvents may help linking the artifact with its SBOM by including a link to the SBOM in the artifact events.
Partially-addresses: #132
> Add an SBOM URI field to artifact events

- .spellcheck-en-custom.txt
- continuous-integration.md
- examples/artifact_deleted.json
- examples/artifact_downloaded.json
- schemas/artifactdeleted.json
- schemas/artifactdownloaded.json
- spec.md
Cleaned up some wrong references, left over when moving test events, added both testing and artifact events to spec.md too. Add the `user` field to the artifact push event and it introduces the artifact pulled and deleted events, both with a `user` field too.
Partially-fixes: #143
> Add user field to artifact events and download and delete events

- cloudevents-binding.md
The current example uses an incosistent type and draft versions. Align the example with the v0.3.0 spec and make it consistent.
Fixes: #178
> Fix the event example in cloudevents-binding

- examples/testcaserun_skipped.json
- schemas/testcaserunskipped.json
- testing-events.md
Adds "skip" to the set of possible outcomes for a testcaserun.finished message. A final outcome of "skip" is common for many test frameworks, so adding it as a possible outcome will improve interoperability.
See further discussion in https://github.com/cdevents/spec/issues/140.
I clicked on all of the links in the submitter checklist, but some seem sort of stale or not very applicable.
> Adds "skip" as a new testcaserun finished outcome

- continuous-operations.md
Update to the ticket event descriptions.
> Update ticket event descriptions

- spec.md
Some examples in the spec use incomplete event types, that do not include the version part. Add the version part to all places where it was missing.
Fixes: #194
> Use complete event types in the spec

- .github/linters/.eslintrc.yml
- .github/workflows/main.yml
- custom/schema.json
- examples/incident_detected.json
- examples/incident_reported.json
- examples/incident_resolved.json
- examples/testcaserun_finished.json
- examples/testoutput_published.json
- examples/testsuiterun_finished.json
- schemas/servicedeployed.json
eslint --fix
This commit addresses some of the inconsistencies in our
JSON files
> Adds JSON linting

- custom/conformance.json
- custom/schema.json
- tools/validate.sh
The custom schema had a few issues to be fixed:
- missing chainId and links from the context
- missing version in the type regex
- replace "." with "\." in the type regex
This PR fixes all those and adds a conformance.json example file to validate against the custom schema.
Fixes #216
> Fix custom schema and add validation

- tools/event-version.sh
- tools/spec-release.sh
Update the scripts in the `tools` folder to account for new files and folders.
> Update tools with new files and folders

- cloudevents-binding.md
- conformance/environment_created.json
- conformance/environment_modified.json
- conformance/pipelinerun_finished.json
- conformance/pipelinerun_queued.json
- conformance/pipelinerun_started.json
- conformance/repository_created.json
- conformance/repository_deleted.json
- conformance/repository_modified.json
- conformance/taskrun_finished.json
- conformance/taskrun_started.json
- links.md
- schemas/environmentcreated.json
- schemas/environmentmodified.json
- schemas/pipelinerunfinished.json
- schemas/pipelinerunqueued.json
- schemas/pipelinerunstarted.json
- schemas/repositorycreated.json
- schemas/repositorydeleted.json
- schemas/repositorymodified.json
- schemas/taskrunfinished.json
- schemas/taskrunstarted.json
- schemas/testsuiterunqueued.json
- spec.md
- define every fields `url` and `viewUrl` with `format: "uri"` as proposed in #191 
- as the version of schema was with suffix `-draft`, I didn't update them
> Define every `url` and `viewUrl` field as format `uri`

- links.md
- spec.md
The links.md and spec.md files had some residual snake casing that did not get fixed. This commit addresses that
Fixes #204
> Fix consistency with casing
